# Generated by Django 3.2.10 on 2024-03-19 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerreviews',
            name='auto_id',
        ),
        migrations.RemoveField(
            model_name='customerreviews',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='customerreviews',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='customerreviews',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='customerreviews',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='customerreviews',
            name='updater',
        ),
    ]
